/**
 * The Truth or Dare bank. Everything in it is meant to be safe to say to a stranger, so:
 *  - text only (the app has no photos or voice), nothing that needs a real-world action;
 *  - nothing sexual or romantic, nothing about anyone's body or looks, no alcohol or drugs;
 *  - no politics, religion, caste or region, and nothing that could hurt;
 *  - nothing that asks for contact details, a real name, a location or a social handle (anonymity is the point of the app).
 * tests/flow.test.ts checks every entry against screenPrompt(), so an addition that breaks these rules fails the tests.
 */
export const TRUTHS: string[] = [
  "What is the most embarrassing song on your playlist?",
  "What is the silliest thing you have ever cried about?",
  "What is a food combination you love that other people find weird?",
  "Which movie have you watched the most times?",
  "What is the worst excuse you have ever used to skip class or work?",
  "What is a talent you have that nobody would guess?",
  "What was the last thing you searched for on the internet?",
  "What is the most useless superpower you can think of?",
  "What is the funniest thing that has ever happened to you in public?",
  "What is the strangest thing you have ever eaten?",
  "If you could swap lives with a fictional character for a day, who would it be?",
  "What is a childhood habit you still have?",
  "What is the worst gift you have ever received?",
  "What is your guilty pleasure TV show?",
  "What is the most childish thing you still do?",
  "What is a lie you told as a kid that you got away with?",
  "What was the last thing that made you laugh out loud?",
  "What is the weirdest dream you remember?",
  "Which app do you spend the most time on, and are you proud of it?",
  "What is the most embarrassing thing that has happened to you on a video call?",
  "What is a rule you always break?",
  "What is something you are secretly good at?",
  "If you could only eat one dish for the rest of your life, what would it be?",
  "What is the most annoying habit of someone you live with?",
  "What was your favourite cartoon as a kid?",
  "What is something you pretend to like but actually do not?",
  "What is the biggest mistake you have made in a group project?",
  "What is the nicest thing a stranger has ever done for you?",
  "What is a skill you wish you could learn overnight?",
  "Have you ever laughed at the worst possible moment? What happened?",
  "What is the strangest thing you have ever bought online?",
  "What is your go-to karaoke song, even if you cannot sing?",
  "What is the most embarrassing nickname you have ever had?",
  "If you were invisible for a day, what harmless prank would you pull?",
  "What is the last lie you told, big or small?",
  "What is something you are afraid of that most people are not?",
  "What is your most-used emoji, and what does it say about you?",
  "What is the most spontaneous thing you have ever done?",
  "What do you do when you cannot sleep?",
  "What was the first thing you bought with your own money?",
  "What is a food you refuse to share?",
  "What is the funniest autocorrect mistake you have ever sent?",
  "What is the most boring thing you have ever pretended to be interested in?",
  "If you could have dinner with any famous person, who would it be and why?",
  "What is the last thing you forgot that you really should have remembered?",
  "What is the worst advice you have ever followed?",
  "What is a weird thing you do when you are alone?",
  "Which fictional place would you most like to visit?",
  "What is something you did as a kid that you now find embarrassing?",
  "What is the best prank you have ever pulled or seen?",
  "What is the most unusual thing you own?",
  "What is your most irrational fear?",
  "Which game could you play for hours without getting bored?",
  "What is something small that instantly improves your mood?",
  "What is the strangest compliment you have ever received?",
  "Have you ever walked into the wrong room or got on the wrong bus? What happened?",
  "What is your hidden talent at get-togethers?",
  "What would you do first if you won a lottery tomorrow?",
  "What is a trend you secretly liked but never admitted?",
  "What is the worst smell you have ever come across?",
  "What is the most useless thing you know by heart?",
  "If you had to teach a class tomorrow, what would the topic be?",
  "What is the worst chore you have ever had to do?",
  "What is the song you have played the most this month?",
  "What is a movie that everyone loves but you did not enjoy?",
  "What is the most ridiculous reason you have ever been late?",
  "If you could teleport anywhere right now, where would you go?",
  "What is something you wish you had said no to?",
  "What is the best thing you have eaten this week?",
  "Which cartoon character are you most like?",
  "What is the strangest thing you have been told you said in your sleep?",
  "What is your biggest \"I cannot believe I did that\" moment?",
  "What is something you are proud of that you rarely talk about?",
  "What is the silliest argument you have ever had?",
  "What is one thing you would change about your daily routine?",
  "What is your comfort food on a bad day?",
  "What would your theme song be?",
  "If animals could talk, which one would be the rudest?",
  "What is the worst thing you have ever cooked?",
  "What is the funniest thing a teacher has ever said to you?",
  "What is something you learned recently that surprised you?",
  "What is the most embarrassing thing you have sent to a group chat by mistake?",
  "If you could live in any decade, which one would it be and why?",
  "What is the most interesting thing you have ever found in a bag or pocket?",
  "What is one silly thing on your bucket list?",
  "What is a word or phrase you say way too often?",
  "What is something you have been putting off this week?",
  "What is the best trick you know to stay awake?",
  "What is the most unusual place you have ever fallen asleep?",
  "What would you name a pet dragon?",
  "What is the worst movie you have ever sat through to the very end?",
  "If you could erase one song from the world, which would it be?",
  "What is the funniest thing your family has done in front of your friends?",
  "What is the last meme you shared?",
  "What is a hobby you tried once and gave up on quickly?",
  "What is the bravest thing you have done recently?",
  "If you were a vegetable, which one would you be and why?",
  "Besides your phone, what is the one thing you would take to a deserted island?",
  "What is the most expensive thing you have ever broken?",
  "What was the silliest rule you had as a child?",
  "What is the last thing you did that made you proud of yourself?",
  "If you could instantly be great at any sport, which one would you pick?",
  "What is the worst thing about mornings for you?",
  "What is a smell that takes you straight back to your childhood?",
  "What does your perfect lazy Sunday look like?",
  "What is the most memorable birthday you have ever had?",
  "What is the weirdest talent you wish you had?",
  "If your life were a movie, what genre would it be?",
  "Which would you give up for a month: sweets or social media?",
  "What is the most ridiculous thing you have ever done to win a game?",
  "What is the funniest thing you have ever seen an animal do?",
  "If you could instantly speak any language, which one would you choose?",
  "What song do you play when you want to feel unstoppable?",
  "What is the funniest message you have ever received?",
  "What is one small thing that always annoys you?",
  "What would be the title of your autobiography?",
  "What is the best piece of advice you have ever been given?",
  "If you could add one subject to every school, what would it be?",
  "What is your most unpopular food opinion?",
  "What is your most unpopular opinion about movies or music?",
];

export const DARES: string[] = [
  "Describe your whole day using only emojis.",
  "Write a two-line poem about the last thing you ate.",
  "Send your next three messages in rhyme.",
  "Type the alphabet backwards in one message.",
  "Tell the worst joke you know.",
  "Pretend to be a news reporter and announce what you are doing right now.",
  "Invent a new word and use it in a sentence.",
  "Write a one-sentence horror story about a missing sock.",
  "Describe your favourite food without saying its name and let your partner guess it.",
  "Reply to your partner's next message in all capital letters.",
  "Write a motivational quote as if you were a very dramatic movie hero.",
  "Talk like a pirate for your next three messages.",
  "Give your partner a superhero name and describe their powers.",
  "Describe the room you are in the way a travel guide would.",
  "Write a story in exactly four words.",
  "Write three sentences that each begin with the letter S.",
  "Give yourself a silly nickname and use it for the rest of the game.",
  "Write a review of the last movie you watched as if you were a very angry critic.",
  "Write a short advertisement for an ordinary object near you.",
  "Pretend to be a robot and answer your next two messages in robot speak.",
  "Imagine what your partner is doing right now and narrate it like a nature documentary.",
  "Write a haiku about Mondays.",
  "Make up a three-word motto for yourself and explain it.",
  "Write a compliment for the last object you touched.",
  "Invent a conspiracy theory about why pigeons exist.",
  "Explain how to make tea or coffee as if you were a wizard casting a spell.",
  "Type your next message without using the letter A.",
  "Write one sentence where every word starts with the same letter.",
  "Make up a band name and the title of its first hit song.",
  "Describe a rainbow to someone who has never seen colours.",
  "Pretend to be your favourite cartoon character for your next two messages.",
  "Tell your partner a fun fact, real or made up, and let them guess which one it is.",
  "Write the opening line of a bestselling novel.",
  "Give a dramatic speech, in text, about why snacks matter.",
  "Rate the last thing you ate out of ten, like a food critic.",
  "Invent a new holiday and describe how people celebrate it.",
  "Describe a sunset using only food words.",
  "Write a two-line rap about your day.",
  "Make up a funny slogan for your partner.",
  "Be a weather forecaster and predict your partner's week.",
  "Write a thank-you note to your phone charger.",
  "Convince your partner that a spoon is better than a fork.",
  "Pitch a ridiculous startup idea in two sentences.",
  "Write a dramatic apology letter from a cat to its owner.",
  "Pick an animal that matches your mood today and explain why.",
  "Tell a story about a lost umbrella in exactly three sentences.",
  "Send a message that is exactly ten words long.",
  "Explain the plot of a famous movie using only emojis and let your partner guess it.",
  "Invent a new ice cream flavour and sell it to your partner.",
  "Write a short message from a time traveller.",
  "Ask only questions for your next three messages.",
  "Write a two-line lullaby for a grumpy dragon.",
  "Commentate, in text, on someone drinking a glass of water, like a sports commentator.",
  "Write a short ghost story where the ghost is afraid of people.",
  "Try to make your partner laugh using a single sentence.",
  "Make up a secret handshake and describe it step by step.",
  "Describe what a dog thinks when it sees a vacuum cleaner.",
  "Write a short poem where every line ends with the same word.",
  "Be a tour guide on the moon and describe one attraction.",
  "Explain how to brush teeth as if you were talking to an alien.",
  "Announce that you have won an imaginary award and give a short speech.",
  "Describe your favourite season as a villain's monologue.",
  "Write a motivational poster caption for a sleepy cat.",
  "Write the menu of a restaurant that only serves food starting with the letter B.",
  "Say \"I am a teapot\" in five different styles.",
  "Narrate your next message in the third person, like a storyteller.",
  "Describe your perfect pizza and defend it against all critics.",
  "Write a very short fairy tale about a sleepy broom.",
  "Describe the greeting \"good morning\" using only emojis and explain your choices.",
  "Describe your mood with five emojis and let your partner guess what each one means.",
  "Invent a superhero whose only power is being slightly early.",
  "Answer your partner's next message like an overexcited game show host.",
  "Make a bold prediction about the world in the year 2100.",
  "Write the shortest mystery story you can.",
  "Describe how you would escape from a room full of marshmallows.",
  "Explain your favourite sport to a penguin who has never seen it.",
  "Write a dramatic reading of the instructions on any bottle or packet near you.",
  "Invent a secret code of three symbols and teach it to your partner.",
  "Type a tongue twister without making a single typo.",
  "Write a five-word review of the last thing you watched.",
  "Give your partner a one-sentence pep talk, like a coach would.",
  "Name three things you could do with a paper clip other than the obvious.",
  "Pretend to be a cat and describe your plans for the afternoon.",
  "Describe the taste of your favourite fruit to an alien.",
  "Make a tiny picture using only keyboard characters.",
  "Write a good-news headline about something silly.",
  "Imagine a talking vending machine and write its first line.",
  "Write a two-line conversation between a tree and a bird.",
  "Write a fan letter to your favourite snack, one sentence only.",
  "Write three tips for surviving a very boring meeting.",
  "Name a made-up animal and describe its strangest habit.",
  "Explain the plot of a famous cartoon in one breathless sentence.",
  "Tell the story of your morning as if it were a thrilling adventure.",
  "Make up a rule for an invented sport and teach it to your partner.",
  "Write a tiny riddle for your partner to solve.",
  "Type a sentence where every word has exactly four letters.",
  "Describe a very ordinary object as if it were a priceless museum treasure.",
  "Answer your partner's next two messages in the voice of a grumpy old wizard.",
  "Write one line of a song about the weather.",
  "Make up an excuse for being late that is so strange it must be true.",
  "Introduce yourself like the narrator of an action movie trailer.",
  "Describe what your phone would say if it could tell you about its day.",
  "Invent a gadget that solves one tiny everyday problem, and name it.",
  "Tell a story about a brave potato in three sentences.",
  "Explain why the sky is blue using only made-up science.",
  "Rank pizza, biryani and noodles from best to worst and defend your order.",
  "Spell your favourite word backwards and make your partner guess it.",
  "Write a wanted poster for a missing left sock.",
  "Describe the happiest sound you can think of.",
  "Make up a short chant for cheering up a friend.",
  "Tell your partner a three-line bedtime story about a sleepy cloud.",
  "Write the argument between two famous cartoon characters about pizza toppings.",
  "Pretend to be a talking houseplant and complain about your owner.",
  "Come up with three silly names for a pet goldfish.",
  "Write a ten-word story about a surprise.",
  "Invent a believable fun fact about the moon and keep a straight face.",
  "Compliment your partner using only words from a language you invent on the spot.",
];
